# Gradle Properties
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Gradle Plugins
loom_version = 1.13-SNAPSHOT
moddev_version = 2.0.80
versioning_version = 1.0.0
kpublish_version = 1.0.0
submodule_version = 0.8.0
remapcheck_version = 0.3.4

# Fabric Properties
# check these on https://fabricmc.net/develop
java_version=21
minecraft_version = 1.21.11-rc2
parchment_mc_version = 1.21.5
parchment_version = 2025.04.19
yarn_version = 1
fabric_loader_version = 0.18.1
neoforge_version = 21.5.0-alpha.1.21.6-pre3.20250606.211300
neoforge_pr = 2297

# Mod Properties
project_version = 2.0.3-beta.0.patbox+1.21.11
maven_group = com.kneelawk.graphlib
archives_base_name = graphlib
javadoc_package_name = com/kneelawk/graphlib

# Dependencies
fapi_version = 0.139.4+1.21.11
codextra_version = 2.0.0+1.21
common_events_version = 1.4.0+1.21.4
lns_version = 0.13.0-pre.1
kml_version = 0.4.3+1.21
knet_version = 1.0.2+1.21

# Runtime Only Dependencies
mod_menu_version = 14.0.0-rc.2

# Javadoc Dependencies
jetbrains_annotations_version = 24.0.0
